logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "comments copy-video-url custom-video-buffer disable-fullscreen-panels disable-player-popup-panels disable-zoom-haptics enable-debugging external-downloads hide-artist-card hide-autoplay-button hide-captions-button hide-email-address hide-endscreen-cards hide-filter-bar hide-info-cards hide-load-more-button hide-player-buttons hide-player-overlay hide-seekbar hide-shorts-components hide-timestamp hide-video-action-buttons navigation-buttons old-quality-layout open-links-externally remove-player-controls-background seekbar-tapping spoof-app-version video-speed"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "client-spoof custom-branding disable-auto-captions disable-shorts-on-startup hdr-auto-brightness hide-ads hide-album-cards hide-breaking-news-shelf hide-cast-button hide-crowdfunding-box hide-floating-microphone-button hide-watch-in-vr hide-watermark minimized-playback premium-heading remember-video-quality return-youtube-dislike sponsorblock swipe-controls tablet-mini-player theme vanced-microg-support video-ads wide-searchbar"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Twitter]
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
build-mode = "apk"
excluded-patches = "playback-speed"
included-patches = "disable-login-requirement downloads feed-filter fix-google-login hide-ads settings show-seekbar sim-spoof"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
build-mode = "apk"
included-patches = "hide-ads hide-subreddit-banner premium-icon-reddit sanitize-sharing-links"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Trakt]
build-mode = "apk"
included-patches = "unlock-pro"
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
included-patches = "unlock-plus"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
